appointmentscheduler/force-app/main/default/objects/PhysicianSpecialization__c/PhysicianSpecialization__c.object-meta.xml
<CustomObject>
    <label>PhysicianSpecialization</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PhysicianSpecializations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

appointmentscheduler/force-app/main/default/objects/PhysicianSpecialization__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>PhysicianSpecializations</relationshipLabel>
    <relationshipName>PhysicianSpecializations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

appointmentscheduler/force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

appointmentscheduler/force-app/main/default/objects/Specialization__c/fields/Consultation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Fee__c</fullName>
    <label>Consultation Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

appointmentscheduler/force-app/main/default/classes/AppointmentSchedulerController.cls
public with sharing class AppointmentSchedulerController {
    @AuraEnabled(cacheable=true)
    public static List<Specialization__c> getSpecializations(){
        try{
        	return [Select Id, Name, Description__c, Consultation_Fee__c, (Select Id, Physician_Name__c, Physician_Email__c from PhysicianSpecializations__r) from Specialization__c];
        }
        catch (AuraHandledException ex){
            System.debug(ex.getStackTraceString());
            throw ex;
        }
        catch (Exception ex){
            System.debug(ex.getStackTraceString());
            throw new AuraHandledException('There was some issue while fetching specialization details');
        }
    }
}